.TH "deprecated" 3 "Thu Jul 25 2024" "Version 2024-07-25" "Library libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBft_aisi\fP (const char *str)\fP" 1c
 This function has been deprecated because it is more stric than \fBft_atoi()\fP which, if used together, adds unnecesary precautions which actually goes against the user\&. Use ft_strisi() instead\&. 
.br
 Additionaly, the function name is misleading since it deals withe a c-string ('str'isi) not a character ('a'isi)\&.
.PP

