.TH "include/ft_debug.h" 3 "Mon Feb 5 2024" "Version 2024-02-05" "Library libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ft_debug.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_print_memory\fP (void *addr, unsigned int size)"
.br
.RI "\fBft_print_memory\fP -- Prints memory content from starting address\&. "
.in -1c
.SH "Detailed Description"
.PP 
Debugging related functions\&. Part of libft library\&. 
.SH "Function Documentation"
.PP 
.SS "void * ft_print_memory (void * addr, unsigned int size)"

.PP
\fBft_print_memory\fP -- Prints memory content from starting address\&. Some_detailed_description\&.TODO\&.
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP - The starting address\&.
.br
\fIsize\fP - The number of consecutive memory bytes to show from addr\&.
.RE
.PP
\fBReturns\fP
.RS 4
TODO\&.
.RE
.PP
\fBWarning\fP
.RS 4
EXTERNAL FUNCTION USED: malloc(), write()\&. 
.br
 TODO\&.
.RE
.PP
\fBRemarks\fP
.RS 4
Implementation notes: 
.br
 TODO\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Library libft from the source code\&.
