.TH "include/ft_math.h" 3 "Sun Feb 4 2024" "Version 2024-01-27" "Library libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ft_math.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_pow\fP (int base, unsigned int exp)"
.br
.RI "\fBft_pow\fP -- Power function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Math related functions\&. Part of libft library\&. 
.SH "Function Documentation"
.PP 
.SS "int ft_pow (int base, unsigned int exp)"

.PP
\fBft_pow\fP -- Power function\&. The pow() functions compute base raised to the power exp\&.
.PP
\fBParameters\fP
.RS 4
\fI-\fP \&.TODO\&.
.RE
.PP
\fBReturns\fP
.RS 4
base^exp\&.
.RE
.PP
\fBWarning\fP
.RS 4
TODO\&.
.RE
.PP
\fBRemarks\fP
.RS 4
Implementation notes: 
.br
 TODO\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Library libft from the source code\&.
