.TH "s_list" 3 "Sat Jan 27 2024" "Version 2024-01-27" "Library libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list \- Base for typedef \fBt_list\fP for a linked list node\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_llst\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBs_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base for typedef \fBt_list\fP for a linked list node\&. 

This type is used as a node for a one-way dynamic linked list\&. Any node could serve as a list for itself (i\&.e\&. as the beginning of a list)\&. 
.SH "Field Documentation"
.PP 
.SS "s_list::content"
Pointer to void to allow caller to use arbitrary type\&. 
.SS "s_list::next"
Pointer to next node of the list\&. NULL if last node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Library libft from the source code\&.
